[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd services/web && npm ci"]

[phases.build]
cmds = ["cd services/web && npm run build"]

[variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://question-production-eaa3.up.railway.app"