[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "DATABASE_URL='postgresql://temp:temp@localhost:5432/temp' npx prisma generate --schema=packages/database/prisma/schema.prisma",
  "npm run build --workspaces --if-present"
]

[start]
cmd = "npm run start"