[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["echo 'Skipping npm install for ultra simple version'"]

[phases.build]
cmds = ["echo 'No build needed for ultra simple version'"]

[variables]
NODE_ENV = "production"