[phases.setup]
nixPkgs = ["nodejs_20", "bash"]

[phases.install]
cmds = ["echo 'Skipping npm install for ultra simple version'"]

[phases.build]
cmds = [
  "chmod +x *.sh",
  "echo 'Railway Simple Build - Skipping complex builds'",
  "echo 'Build completed at:' && date"
]

[variables]
NODE_ENV = "production"