[phases.setup]
nixPkgs = ["nodejs_20", "bash"]

[phases.install]
cmds = ["npm ci --workspace-root --workspaces"]

[phases.build]
cmds = [
  "chmod +x *.sh",
  "DATABASE_URL='postgresql://temp:temp@localhost:5432/temp' npx prisma generate --schema=packages/database/prisma/schema.prisma",
  "npm run build:sequential",
  "echo 'Build completed at:' && date"
]

[start]
cmd = "npm run start:api:with-migrate"

[variables]
NODE_ENV = "production"