[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate --schema=packages/database/prisma/schema.prisma",
  "npm run build --workspaces --if-present"
]

[start]
cmd = "npm run start"