# Railway.app TOML Configuration
# https://docs.railway.app/reference/config-as-code

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./start-api.sh"
healthcheckPath = "/health"
healthcheckInterval = 30
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3