# Railway.app TOML Configuration
# https://docs.railway.app/reference/config-as-code

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node railway-ultra-simple.js"
healthcheckPath = "/health"
healthcheckInterval = 30
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3