# Railway.app TOML Configuration
# https://docs.railway.app/reference/config-as-code

[build]
builder = "NIXPACKS"
buildCommand = "cd services/web && npm ci && npm run build"

[deploy]
startCommand = "cd services/web && npm run start"
healthcheckPath = "/"
healthcheckInterval = 30
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3