[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:api:with-migrate"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10