# Railway.app configuration for Next.js frontend
[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckInterval = 30
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://question-production-eaa3.up.railway.app"