# Railway configuration for API service
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node railway-api.js"
healthcheckPath = "/health"
healthcheckInterval = 30
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3