[build]
builder = "nixpacks"

[build.env]
NPM_CONFIG_PRODUCTION = "false"

[deploy]
startCommand = "cd services/api && npm run migrate && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10